### PR TITLE
Update Scala Native to 0.4.0

### PR DESCRIPTION
**Pull request by lolgab**
The only missing part is `SDL_SetError` that uses `...` varargs that are not supported on Scala Native 0.4.0-M2.
It is implemented in the C source using `va_list`, which is supported in through `CVarArgList`, but I didn't spend time to reimplement it in using CVarArgList.

### CODE REVIEW

**Comment by lolgab** [comment]
This is now ready for review.
@regb are there chances to have a review or we need to fork the project?
Thank you in advance.

**Comment by regb** [comment]
Hi, yes sorry I will take a look later today!

**Comment by lolgab** [comment]
Thank you @regb !

**Comment by regb** [comment]
I have some trouble to get the examples to work on your branch.

I'm working through examples/opengl-setup

The first changes I had to make is to update the build.properties and plugins.sbt with the same versions as the updates in the root project. Could you add a commit to update these in all examples? I know it's a bit annoying having to keep all of them in sync, it would be nice to find a way for all of them to share the same config..

But even after these changes I get some compile errors (if you run sbt compile from inside the examples/opengl-setup).

[error] /home/reg/vcs/games/scalanative-graphics-bindings/examples/opengl-setup/Main.scala:56:15: not found: type UByte
[error]     val test: UByte = (SDL_MapRGB(surface.format, 0xAA.toUByte, 0xBB.toUByte, 0XCC.toUByte) & 0xFF.toUInt).toUByte
[error]               ^

I was able to figure out that we must import scalanative.unsigned.UByte in order to fix this. But then the compiler is still complaining about the toUByte that doesn't exist, I wasn't able to figure out what happened to this function with the move to 0.4

I'll look more into it tomorrow, but in any case, thanks for updating this to scala-native 0.4 ! I haven't been following changes in Scala for quite some time so I'll need to catch up a bit.

**Comment by lolgab** [comment]
Sure, I completely overlooked the examples!
About the unsigned problem, you need to import the implicit classes with `import scala.scalanative.unsigned._` to have `.toUByte` work.
I will have a look when I have some time.

**Comment by lolgab** [comment]
@regb Updated the examples too.
I ran some of them ( snake and the opengl 3d cube ) and they work correctly.
For some I missed the dependencies ttf one.
I think now everything is ok to merge and release a new version :)

**Comment by regb** [comment]
Awesome, thanks a lot. I will merge and release a new version

**Comment by regb** [comment]
I just released the changes with version 0.2 on Maven Central.

**Comment by lolgab** [comment]
Thank you!

**Pull request merged**
